# Generated by Django 4.2.3 on 2024-07-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.SmallIntegerField()),
                ('size_m2', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.SmallIntegerField()),
                ('address', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcs.apartment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('type',), name='hcs_tariff_unique'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('number', 'address'), name='hcs_building_unique'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcs.building'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('number', 'building_id'), name='hcs_apartment_unique'),
        ),
    ]
