# Generated by Django 4.2.3 on 2024-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingservicelog',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watermeterlog',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
