# Generated by Django 4.2.3 on 2024-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apartment',
            name='hcs_apartment_unique',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='watermeter',
            old_name='apartment_id',
            new_name='apartment',
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('number', 'building'), name='hcs_apartment_unique'),
        ),
    ]
